name: smartmob
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=2.1.0=py_0
  - asn1crypto=0.24.0=py36_0
  - branca=0.3.0=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_0
  - cryptography=2.2.1=py36_0
  - fiona=1.7.12=py36_0
  - folium=0.5.0=py_0
  - gdal=2.2.4=py36_0
  - geographiclib=1.49=py_0
  - geopandas=0.3.0=py36_0
  - geopy=1.14.0=py_0
  - idna=2.7=py36_0
  - networkx=2.1=py36_0
  - openssl=1.0.2o=0
  - osmnx=0.8.1=py_0
  - pycparser=2.18=py36_0
  - pyopenssl=18.0.0=py36_0
  - pysocks=1.6.8=py36_1
  - requests=2.19.1=py36_0
  - toolz=0.9.0=py_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36_0
  - vincent=0.4.4=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.3=py36_0
  - bzip2=1.0.6=h14c3975_5
  - cairo=1.14.12=h7636065_2
  - click=6.7=py36h5253387_0
  - click-plugins=1.0.3=py36_0
  - cligj=0.4.0=py36_0
  - curl=7.60.0=h84994c4_0
  - cycler=0.10.0=py36h93f1223_0
  - cython=0.28.3=py36h14c3975_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - descartes=1.1.0=py36h2f9c1c0_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - freexl=1.0.5=h14c3975_0
  - geos=3.6.2=heeff764_2
  - giflib=5.1.4=h26a3ec6_1
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.1=h9caa474_1
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10=py36ha16c418_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - kealib=1.4.7=h79811e5_5
  - kiwisolver=1.0.1=py36h764f252_0
  - krb5=1.16.1=hc83ff2d_6
  - libboost=1.65.1=habcd387_4
  - libcurl=7.60.0=h1ad7b7a_0
  - libdap4=3.19.0=h5bd89bb_2
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgdal=2.2.4=hc8d23f9_1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libkml=1.3.0=h9d32c78_3
  - libnetcdf=4.4.1.1=h816af47_8
  - libpng=1.6.34=hb9fc6fc_0
  - libpq=10.3=h1ad7b7a_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.8.5=h20b78c2_2
  - libspatialite=4.3.0a=h72746d6_18
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.2.2=py36h0e671d2_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - munch=2.3.2=py36_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - ncurses=6.1=hf484d3e_0
  - notebook=5.5.0=py36_0
  - numpy=1.14.5=py36hcd700cb_0
  - numpy-base=1.14.5=py36hdbf6ddf_0
  - openjpeg=2.3.0=h05c96fa_1
  - pandas=0.23.1=py36h637b7d7_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.2.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - poppler=0.65.0=ha54bb34_0
  - poppler-data=0.4.9=0
  - proj4=4.9.3=hc8507d1_7
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - psycopg2=2.7.4=py36hb7f436b_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pygments=2.2.0=py36h0d3125c_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyproj=1.9.5.1=py36_0
  - pyqt=5.9.2=py36h751905a_0
  - pysal=1.14.3=py36_0
  - python=3.6.5=hc3d631a_2
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - pyzmq=17.0.0=py36h14c3975_0
  - qt=5.9.5=h7e424d6_0
  - qtconsole=4.3.1=py36h8f73b5b_0
  - readline=7.0=ha6073c6_4
  - rtree=0.8.3=py36h2f9c1c0_0
  - scipy=1.1.0=py36hfc37229_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.2.0=py36_0
  - shapely=1.6.4=py36h0c48222_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36h372c433_1
  - sqlalchemy=1.2.8=py36h14c3975_0
  - sqlite=3.23.1=he433501_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h8cadb63_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h674d592_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xerces-c=3.2.1=hac72e42_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - boto3==1.7.45
    - botocore==1.10.45
    - docutils==0.14
    - geojson==2.4.0
    - jmespath==0.9.3
    - pymongo==3.6.1
    - python-dotenv==0.8.2
    - s3transfer==0.1.13
prefix: /home/sepud/miniconda3/envs/smartmob

